-- ALTER TYPE "organization_config_key" ADD VALUE 'primary_color';--> statement-breakpoint
-- ALTER TYPE "organization_config_key" ADD VALUE 'secondary_color';--> statement-breakpoint
-- ALTER TYPE "organization_config_key" ADD VALUE 'tagline';--> statement-breakpoint
-- ALTER TABLE "organizations" ADD COLUMN "phone_number" text;--> statement-breakpoint
-- ALTER TABLE "organizations" ADD COLUMN "email" text;--> statement-breakpoint
-- ALTER TABLE "users" ADD COLUMN "phone_number" text;