name: Generate Migrations

on:
  push:
  workflow_dispatch:

jobs:
  generate-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Pull changes
        run: git pull origin ${{ github.ref }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
      - name: Install dependencies
        run: pnpm install
      - name: Generate migrations
        run: pnpm run db:generate
      - name: Commit and push migrations
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generate new migrations [skip ci]" -m "Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" || echo "No changes to commit"
          git push origin ${{ github.ref }}
