name: Setup Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  create-db:
    runs-on: ubuntu-latest
    environment: "Preview"
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Load DB_URL from secrets
        run: echo "DB_URL=${{ secrets.DB_URL }}/pr${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create database
        run: |
          psql "${{ secrets.DB_URL }}/postgres" -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'pr${{ github.event.number }}' AND pid <> pg_backend_pid();"
          psql "${{ secrets.DB_URL }}/postgres" -c 'drop database if exists "pr${{ github.event.number }}";'
          psql "${{ secrets.DB_URL }}/postgres" -c 'create database "pr${{ github.event.number }}";'
      - name: Migrate database
        run: pnpm run db:migrate
      - name: Seed database
        run: pnpm run db:seed
