name: Setup Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  create-db:
    runs-on: ubuntu-latest
    environment: "Preview"
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Load DB_URL from secrets
        run: echo "DB_URL=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create database
        run: |
          PGPASSWORD="${{ secrets.DB_PASSWORD }}" psql -h ${{ secrets.DB_HOST }} -p ${{ secrets.DB_PORT }} -U ${{ secrets.DB_USER }} -d postgres -c 'create database "${{ github.ref_name }}";'

      - name: Migrate database
        run: pnpm run db:migrate
