name: Setup Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  create-db:
    runs-on: ubuntu-latest
    environment: "Preview"
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Load DB_URL from secrets
        run: echo "DB_URL=${{ secrets.DB_URL }}/pr${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create database
        run: |
          psql "${{ secrets.DB_URL }}/postgres" -tAc "SELECT 1 FROM pg_database WHERE datname = 'pr${{ github.event.number }}'" | grep -q 1 || \
            psql "${{ secrets.DB_URL }}/postgres" -c 'create database "pr${{ github.event.number }}";'
      - name: Migrate database
        run: pnpm run db:migrate
      - name: Seed database
        run: pnpm run db:seed
      - name: Setup Juno File Storage
        run: pnpm run setupJunoFileStorage
        env:
          JUNO_API_KEY: ${{ secrets.JUNO_API_KEY }}
          JUNO_BASE_URL: ${{ vars.JUNO_BASE_URL }}
          FILE_PROVIDER_NAME: ${{ vars.FILE_PROVIDER_NAME }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          JUNO_PROJECT_ID: ${{ secrets.JUNO_PROJECT_ID }}
          JUNO_FILE_BUCKET_PREFIX: ${{ vars.JUNO_FILE_BUCKET_PREFIX }}
          SETUP_ORGANIZATION_ID: ${{ vars.SETUP_ORGANIZATION_ID }}
      - name: Setup organization
        run: pnpm run setupOrg
        env:
          JUNO_API_KEY: ${{ secrets.JUNO_API_KEY }}
          JUNO_BASE_URL: ${{ vars.JUNO_BASE_URL }}
          FILE_PROVIDER_NAME: ${{ vars.FILE_PROVIDER_NAME }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          JUNO_PROJECT_ID: ${{ secrets.JUNO_PROJECT_ID }}
          JUNO_FILE_BUCKET_PREFIX: ${{ vars.JUNO_FILE_BUCKET_PREFIX }}
          SETUP_ORGANIZATION_ID: ${{ vars.SETUP_ORGANIZATION_ID }}
