name: Teardown Preview

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  drop-db:
    runs-on: ubuntu-latest
    environment: "Preview"
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Drop database
        run: |
          psql "${{ secrets.DB_URL }}/postgres" -c 'drop database with (force) if exists "${{ github.ref_name }}";'
